src/main/java/org/D7noun/model/AttachmentItem.java
package org.D7noun.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

@NamedQueries({
		//@NamedQuery(name = AttachmentItem.getAttacmentsByFileId, query = "SELECT attach FROM AttachmentItem attach where attach.item.id = ?1 ORDER BY attach.size asc"),
		@NamedQuery(name = AttachmentItem.findById, query = "SELECT attach FROM AttachmentItem attach WHERE attach.id = ?1") })
@Entity(name="AttachmentItem")
public class AttachmentItem implements Serializable {

	/**
	 * 
	 */

	public static final String getAttacmentsByFileId = "AttachmentItem.getAttacmentsByFileId";
	public static final String findById = "AttachmentItem.findById";

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;

	@Column(nullable=false)
	private String fileName;
	private String contentType;
	private long size;
	@Column(nullable=false)

	private String description;
	private String notes;

	@Lob
	private byte[] data;

	

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the fileName
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * @param fileName
	 *            the fileName to set
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * @return the contentType
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * @param contentType
	 *            the contentType to set
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * @return the size
	 */
	public long getSize() {
		return size;
	}

	public String getSizeInMegaByte() {
		long fraction = 1024;
		double sizeDouble = size;
		if (size != 0) {
			double sizeFraction = sizeDouble / fraction;
			sizeFraction = Math.floor(sizeFraction * 100) / 100;
			return sizeFraction + " KB";
		}
		return "0 MB";
	}

	/**
	 * @param size
	 *            the size to set
	 */
	public void setSize(long size) {
		this.size = size;
	}

	/**
	 * @return the data
	 */
	public byte[] getData() {
		return data;
	}

	/**
	 * @param data
	 *            the data to set
	 */
	public void setData(byte[] data) {
		this.data = data;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *            the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * @param notes
	 *            the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

}

src/main/java/org/D7noun/model/RentalCard.java
package org.D7noun.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

@NamedQueries({
		@NamedQuery(name = RentalCard.getRentalCardsByItem, query = "SELECT r FROM RentalCard r WHERE r.item = :item"),
		@NamedQuery(name = RentalCard.deleteRentalCardsByItem, query = "DELETE FROM RentalCard r WHERE r.item = :item") })
@Entity(name="RentalCard")
public class RentalCard implements Serializable {

	public static final String getRentalCardsByItem = "getRentalCardsByItem";
	public static final String deleteRentalCardsByItem = "deleteRentalCardsByItem";

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;
	@Version
	@Column(name = "version")
	private int version;

	@Column
	@Temporal(TemporalType.DATE)
	private Date startDate;

	@Column
	@Temporal(TemporalType.DATE)
	private Date endDate;

	@Column
	@Temporal(TemporalType.DATE)
	private Date dueDate;

	@OneToOne(targetEntity=Person.class,cascade = CascadeType.MERGE)
	private Person user;


	@Column(length = 1000)
	private String note;

	@OneToOne(targetEntity=Item.class,cascade = CascadeType.MERGE)
	private Item item;

	@OneToMany(targetEntity=AttachmentRentalCard.class,mappedBy = "rentalCard", cascade = CascadeType.MERGE, orphanRemoval = true, fetch = FetchType.EAGER)
	private Set<AttachmentRentalCard> attachments = new HashSet<AttachmentRentalCard>();

	public Long getId() {
		return this.id;
	}

	public void setId(final Long id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(final int version) {
		this.version = version;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!(obj instanceof RentalCard)) {
			return false;
		}
		RentalCard other = (RentalCard) obj;
		if (id != null) {
			if (!id.equals(other.id)) {
				return false;
			}
		}
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getDueDate() {
		return dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public Person getUser() {
		return user;
	}

	public void setUser(Person user) {
		this.user = user;
	}


	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public void newUser() {
		this.user = new Person();
	}

	
	public Item getItem() {
		return item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Override
	public String toString() {
		String result = getClass().getSimpleName() + " ";
		if (note != null && !note.trim().isEmpty())
			result += "note: " + note;
		return result;
	}

	/**
	 * @return the attachments
	 */
	public Set<AttachmentRentalCard> getAttachments() {
		return attachments;
	}

	/**
	 * @param attachments
	 *            the attachments to set
	 */
	public void setAttachments(Set<AttachmentRentalCard> attachments) {
		this.attachments = attachments;
	}

}

src/main/java/org/D7noun/view/ItemBean.java
package org.D7noun.view;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.event.PhaseId;
import javax.inject.Named;
import javax.print.DocFlavor.STRING;

import org.D7noun.facade.AttachmentItemFacade;
import org.D7noun.facade.ItemFacade;
import org.D7noun.model.AttachmentItem;
import org.D7noun.model.Item;
import org.D7noun.model.Unit;
import org.D7noun.model.Item.State;
import org.omnifaces.util.Ajax;
import org.omnifaces.util.Faces;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 * Backing bean for Item entities.
 * <p/>
 * This class provides CRUD functionality for all Item entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD
 * framework or custom base class.
 */

@Named
@SessionScoped
public class ItemBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@EJB
	private ItemFacade itemFacade;

	private Long id;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	private Item item;

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public String create() {

		this.id = null;

		return "create?faces-redirect=true";
	}

	public void retrieve() {

		if (FacesContext.getCurrentInstance().isPostback()) {
			return;
		}

		if (this.id == null) {
			this.item = this.example;
		} else {
			this.item = findById(getId());

		}

	}

	public String clearSearch() {
		this.example = new Item();
		return null;
	}

	public Item findById(Long id) {

		return itemFacade.find(id);

	}

	public Item findBySerialNumber(String serialNumber) {

		return itemFacade.findBySerialNumber(serialNumber);
	}

	/*
	 * Support updating and deleting Item entities
	 */
	public boolean validString(String s) {

		if (s == null || s.isEmpty() || s.trim().isEmpty()) {

			return false;
		}
		return true;
	}

	public String update() {

		if (accessories != null && !accessories.isEmpty()) {
			for (Item accessory : convertsIdsIntoItems(accessories)) {
				this.item.addAccessory(accessory);
			}
		}
		try {
			this.item = itemFacade.save(this.item);
			this.example = new Item();
			return "search?faces-redirect=true";
		} catch (Exception e) {
			if (e.getCause() != null && e.getCause().getCause() != null && e.getCause().getCause().getCause() != null) {

				if (e.getCause().getCause().getCause().getMessage().contains("item_deviceid_key"))
					FacesContext.getCurrentInstance().addMessage(null,
							new FacesMessage("there is already an item with this deviceId"));
				else if (e.getCause().getCause().getCause().getMessage().contains("item_name_key"))
					FacesContext.getCurrentInstance().addMessage(null,
							new FacesMessage("there is already an item with this name"));
				else
					FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			} else {
				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			}
			return null;
		}
	}

	public String delete() {

		try {
			Item deletableEntity = findById(getId());

			if (deletableEntity.getState() == State.damaged) {
				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Is Damaged"));
				return null;
			}
			if (deletableEntity.getState() == State.rented) {
				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Is Rented"));
				return null;
			}
			if (deletableEntity.getState() == State.under_maintenance) {
				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Under Maintenance"));
				return null;
			}
			itemFacade.remove(deletableEntity);

			return "search?faces-redirect=true";
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}

	/*
	 * Support searching Item entities with pagination
	 */

	private int page;
	private long count;
	private List<Item> pageItems;

	private Item example = new Item();

	public int getPage() {
		return this.page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getPageSize() {
		return 10;
	}

	public Item getExample() {
		return this.example;
	}

	public void setExample(Item example) {
		this.example = example;
	}

	public String search() {
		this.page = 0;
		return null;
	}

	public void paginate() {

		this.count = itemFacade.getCount(this.example);

		this.pageItems = itemFacade.getPaginatedList(this.page, getPageSize(), this.example);

	}

	public List<Item> getPageItems() {
		return this.pageItems;
	}

	public long getCount() {
		return this.count;
	}

	public List<Item> getAll() {

		return itemFacade.getAll();
	}

	public Converter getConverter() {

		return new Converter() {

			@Override
			public Object getAsObject(FacesContext context, UIComponent component, String value) {

				return itemFacade.find(Long.valueOf(value));
			}

			@Override
			public String getAsString(FacesContext context, UIComponent component, Object value) {

				if (value == null) {
					return "";
				}

				return String.valueOf(((Item) value).getId());
			}
		};
	}

	/*
	 * Support adding children to bidirectional, one-to-many tables
	 */

	private Item add = new Item();

	public Item getAdd() {
		return this.add;
	}

	public Item getAdded() {
		Item added = this.add;
		this.add = new Item();
		return added;
	}

	/**
	 * D7noun
	 *********************************************************************/

	List<String> accessories = new ArrayList<>();

	public List<Item> getAllAvailableItems() {
		return itemFacade.getAllAvailableItems(this.id);
	}

	public List<Item> getAccessoriesByItemSerialNumber(String serialNumber) {
		return itemFacade.getAccessoriesByItemSerialNumber(serialNumber);
	}

	public List<Item> convertsIdsIntoItems(List<String> ids) {
		List<Item> items = new ArrayList<Item>();
		for (String id : ids) {
			items.add(findBySerialNumber(id));
		}
		return items;
	}

	public void handleFileUpload(FileUploadEvent event) {
		try {

			UploadedFile uploadedFile = event.getFile();

			AttachmentItem attachment = new AttachmentItem();
			attachment.setFileName(uploadedFile.getFileName());
			attachment.setSize(uploadedFile.getSize());
			attachment.setContentType(uploadedFile.getContentType());
			attachment.setData(uploadedFile.getContents());
			item.getAttachments().add(attachment);
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("ItemBean: handleFileUpload");
		}
	}

	public void download(AttachmentItem attachment) {

		try {
			Faces.sendFile(attachment.getData(), attachment.getFileName(), true);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	@EJB
	private AttachmentItemFacade attachmentFacade;
	private AttachmentItem attachmentFordelete;

	public void selectForDelete(AttachmentItem attachment) {
		attachmentFordelete = attachment;
	}

	public void deleteAttachment() {
		try {
			item.getAttachments().remove(attachmentFordelete);
		} catch (Exception exception) {
			exception.printStackTrace();
		}
	}

	public StreamedContent getPicture() {
		FacesContext context = FacesContext.getCurrentInstance();

		if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
			return new DefaultStreamedContent();
		} else {
			String attachmentId = context.getExternalContext().getRequestParameterMap().get("attachmentId");
			if (attachmentId != null) {
				AttachmentItem attachmentItem = attachmentFacade.findById(Long.parseLong(attachmentId));
				StreamedContent streamedContent = new DefaultStreamedContent(
						new ByteArrayInputStream(attachmentItem.getData()));
				return streamedContent;
			}
		}
		return new DefaultStreamedContent();
	}

	/**
	 * @return the accessories
	 */
	public List<String> getAccessories() {
		return accessories;
	}

	/**
	 * @param accessories
	 *            the accessories to set
	 */
	public void setAccessories(List<String> accessories) {
		this.accessories = accessories;
	}

}

src/main/webapp/rentalCard/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:forgeview="http://jboss.org/forge/view"
	xmlns:p="http://primefaces.org/ui"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{rentalCardBean.id}' />
		<f:event type="preRenderView" listener='#{rentalCardBean.retrieve}' />
	</f:metadata>

	<ui:param name="pageTitle" value="Create Rental Card" />

	<ui:define name="header">
		Rental Card
	</ui:define>

	<ui:define name="subheader">
		<c:choose>
			<c:when test='#{!empty rentalCardBean.id}'>
				Edit existing Rental Card
			</c:when>
			<c:otherwise>
				Create a new Rental Card
			</c:otherwise>
		</c:choose>
	</ui:define>

	<ui:define name="footer" />

	<ui:define name="main">

		<h:outputStylesheet name="font-awesome/css/font-awesome.css" />

		<h:form id="create">

			<h:outputStylesheet name="css/attachment.css" />
			<h:outputStylesheet name="css/selectOneMenu.css" />

			<h:messages globalOnly="true" styleClass="error" />

			<div class="col-md-6">
				<div class="row">

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="rentalCardBeanRentalCardStartDate" value="Start Date:" />
							</div>
							<div class="col-md-7">
								<p:calendar id="rentalCardBeanRentalCardStartDate"
									value="#{rentalCardBean.rentalCard.startDate}">
								</p:calendar>
								<h:message for="rentalCardBeanRentalCardStartDate"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="rentalCardBeanRentalCardEndDate" value="End Date:" />
							</div>
							<div class="col-md-7">
								<p:calendar id="rentalCardBeanRentalCardEndDate"
									value="#{rentalCardBean.rentalCard.endDate}">
								</p:calendar>
								<h:message for="rentalCardBeanRentalCardEndDate"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="rentalCardBeanRentalCardDueDate" value="Due Date:" />
							</div>
							<div class="col-md-7">
								<p:calendar id="rentalCardBeanRentalCardDueDate"
									value="#{rentalCardBean.rentalCard.dueDate}">
								</p:calendar>
								<h:message for="rentalCardBeanRentalCardDueDate"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label" value="User:" />
							</div>
							<div class="col-md-7">
								<p:selectOneMenu value="#{rentalCardBean.rentalCard.user}"
									filter="true" filterMatchMode="contains"
									converter="#{personConverter}">
									<f:selectItem />
									<f:selectItems value="#{personBean.all}" var="person"
										itemLabel="#{person.name}" itemValue="#{person}" />
								</p:selectOneMenu>
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel for="rentalCardBeanRentalCardItem"
									styleClass="control-label" value="Item: *" />
							</div>
							<div class="col-md-7">
								<p:selectOneMenu id="rentalCardBeanRentalCardItem"
									value="#{rentalCardBean.rentalCard.item}" filter="true"
									filterMatchMode="contains" converter="#{itemConverter}"
									required="true" requiredMessage="Empty Rented Item">
									<f:selectItem />
									<f:selectItems value="#{itemBean.allAvailableItems}" var="item"
										itemLabel="#{item.displayName()}" itemValue="#{item}" />
								</p:selectOneMenu>
								<h:message for="rentalCardBeanRentalCardItem" styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label" value="Project:" />
							</div>
							<div class="col-md-7">
								<p:selectOneMenu value="#{rentalCardBean.rentalCard.project}"
									filter="true" filterMatchMode="contains"
									converter="#{projectConverter}">
									<f:selectItem />
									<f:selectItems value="#{projectBean.all}" var="project"
										itemLabel="#{project.name}" itemValue="#{project}" />
								</p:selectOneMenu>
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="rentalCardBeanRentalCardNote" value="Note:" />
							</div>
							<div class="col-md-7">
								<h:inputTextarea styleClass="form-control textArea"
									id="rentalCardBeanRentalCardNote"
									value="#{rentalCardBean.rentalCard.note}" />
								<h:message for="rentalCardBeanRentalCardNote" styleClass="error" />
							</div>
						</div>
					</div>

				</div>
			</div>

			<div class="col-md-6">

				<p:dataTable id="attachmentsDataTable" widgetVar="attachmentVar"
					rows="5" paginator="true"
					paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
					rowsPerPageTemplate="5,10,15,20,50" paginatorAlwaysVisible="false"
					paginatorPosition="bottom"
					value="#{rentalCardBean.rentalCard.attachments}" var="attachment"
					rowKey="#{attachment.id}" rowIndexVar="index" editable="true"
					editMode="cell">

					<f:facet name="header">

						<h:outputText value="Attachments"
							styleClass="attachmentHeaderText" />

						<p:fileUpload widgetVar="fileUploadVar" multiple="true"
							auto="true" styleClass="fileUploader hide"
							fileUploadListener="#{rentalCardBean.handleFileUpload}"
							process="@this" update="attachmentsDataTable" />

						<h:commandLink onclick="$('.fileUploader input').click()" style=""
							styleClass="btn btn-sm btn-primary attachmentHeaderButton">
							<f:ajax />
							<i class="fa fa-plus white" />
						</h:commandLink>

					</f:facet>

					<p:column id="index" width="50">
						<h:outputText value="#{index+1}"></h:outputText>
					</p:column>

					<p:column id="actions" width="50">
						<h:commandLink styleClass="btn btn-sm btn-danger"
							action="#{rentalCardBean.selectForDelete(attachment)}"
							onclick="PF('deleteDialogVar').show()">
							<i class="fa fa-trash white" />
							<f:ajax />
						</h:commandLink>
					</p:column>

					<p:column id="attachmentName" headerText="Name"
						filterMatchMode="contains" filterBy="#{attachment.fileName}"
						sortBy="#{attachment.fileName}" styleClass="attachmentName-column"
						width="">
						<h:outputText value="#{attachment.fileName}"
							title="#{attachment.fileName}" />
					</p:column>

					<p:column id="attachmentSize" headerText="Size"
						sortBy="#{attachment.size}" style="text-align: center">
						<h:outputText value="#{attachment.sizeInMegaByte}"
							title="#{attachment.sizeInMegaByte}" />
					</p:column>

					<p:column id="description" headerText="Description"
						filterMatchMode="contains" filterBy="#{attachment.description}"
						sortBy="#{attachment.description}"
						styleClass="attachmentDescription-column">
						<h:inputText value="#{attachment.description}"
							styleClass="form-control" />
					</p:column>

					<p:column id="notes" headerText="Notes" filterMatchMode="contains"
						filterBy="#{attachment.notes}" sortBy="#{attachment.notes}"
						styleClass="attachmentNotes-column">
						<h:inputText value="#{attachment.notes}" styleClass="form-control" />
					</p:column>

					<p:column width="50">
						<h:commandLink action="#{rentalCardBean.download(attachment)}"
							styleClass="btn btn-sm btn-primary">
							<i class="fa fa-download white" />
						</h:commandLink>
					</p:column>

				</p:dataTable>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="buttons">
						<h:commandLink value="Save" action='#{rentalCardBean.update}'
							styleClass="btn btn-primary" />
						<c:choose>
							<c:when test='#{!empty rentalCardBean.id}'>
								<h:link value="Cancel" outcome="search"
									styleClass="btn btn-warning">
								</h:link>
								<h:commandLink value="Delete" action='#{rentalCardBean.delete}'
									styleClass="btn btn-danger" />
							</c:when>
							<c:otherwise>
								<h:link value="Cancel" outcome="search"
									styleClass="btn btn-warning" />
							</c:otherwise>
						</c:choose>
						<p:commandLink value="Print" action="#{rentalCardBean.print()}"
							styleClass="btn btn-info" ajax="false">
						</p:commandLink>
					</div>
				</div>
			</div>

			<script type="text/javascript" src="../resources/js/selectOneMenu.js" />
			<script type="text/javascript" src="../resources/js/calendar.js" />

			<p:dialog id="deleteDialog" draggable="false" closable="false"
				modal="true" height="50" width="310" resizable="false"
				widgetVar="deleteDialogVar">

				<f:facet name="header">
					<h:outputText value="Confirm Deletion????" />
				</f:facet>

				<h:commandLink value="Ok"
					action="#{rentalCardBean.deleteAttachment()}"
					onclick="PF('deleteDialogVar').hide()"
					styleClass="btn btn-sm btn-primary popup-buttons">
					<f:ajax render="attachmentsDataTable" />
				</h:commandLink>
				<h:commandLink value="Cancel"
					styleClass="btn btn-sm btn-danger popup-buttons"
					onclick="PF('deleteDialogVar').hide()">
					<f:ajax />
				</h:commandLink>

			</p:dialog>
		</h:form>
	</ui:define>

</ui:composition>