src/main/java/org/D7noun/model/AttachmentItem.java
package org.D7noun.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

@NamedQueries({
		//@NamedQuery(name = AttachmentItem.getAttacmentsByFileId, query = "SELECT attach FROM AttachmentItem attach where attach.item.id = ?1 ORDER BY attach.size asc"),
		@NamedQuery(name = AttachmentItem.findById, query = "SELECT attach FROM AttachmentItem attach WHERE attach.id = ?1") })
@Entity(name="AttachmentItem")
public class AttachmentItem implements Serializable {

	/**
	 * 
	 */

	public static final String getAttacmentsByFileId = "AttachmentItem.getAttacmentsByFileId";
	public static final String findById = "AttachmentItem.findById";

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;

	@Column(nullable=false)
	private String fileName;
	private String contentType;
	private long size;
	@Column(nullable=false)

	private String description;
	private String notes;

	@Lob
	private byte[] data;

	

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the fileName
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * @param fileName
	 *            the fileName to set
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * @return the contentType
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * @param contentType
	 *            the contentType to set
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * @return the size
	 */
	public long getSize() {
		return size;
	}

	public String getSizeInMegaByte() {
		long fraction = 1024;
		double sizeDouble = size;
		if (size != 0) {
			double sizeFraction = sizeDouble / fraction;
			sizeFraction = Math.floor(sizeFraction * 100) / 100;
			return sizeFraction + " KB";
		}
		return "0 MB";
	}

	/**
	 * @param size
	 *            the size to set
	 */
	public void setSize(long size) {
		this.size = size;
	}

	/**
	 * @return the data
	 */
	public byte[] getData() {
		return data;
	}

	/**
	 * @param data
	 *            the data to set
	 */
	public void setData(byte[] data) {
		this.data = data;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *            the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * @param notes
	 *            the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

}

src/main/java/org/D7noun/model/Maintainence.java
package org.D7noun.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

@NamedQueries({
		@NamedQuery(name = Maintainence.getMaintenanceCardsByItem, query = "SELECT m FROM Maintainence m WHERE m.item = :item"),
		@NamedQuery(name = Maintainence.deleteMaintenanceCardsByItem, query = "DELETE FROM Maintainence m WHERE m.item = :item") })
@Entity(name="Maintainence")
public class Maintainence implements Serializable {

	public static final String getMaintenanceCardsByItem = "getMaintenanceCardsByItem";
	public static final String deleteMaintenanceCardsByItem = "deleteMaintenanceCardsByItem";

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;
	@Version
	@Column(name = "version")
	private int version;

	@OneToOne(targetEntity=Item.class,cascade = CascadeType.MERGE)
	private Item item;

	@Column
	@Temporal(TemporalType.DATE)
	private Date startDate;

	@Column
	@Temporal(TemporalType.DATE)
	private Date endDate;

	@Column
	@Temporal(TemporalType.DATE)
	private Date dueDate;

	@Column
	private String malfunctioning;

	@Column
	private Double fees;

	@ManyToOne(targetEntity=Company.class)
	private Company maintenanceCompany;

	@Column
	private String maintenanceMan;

	@OneToMany(targetEntity=AttachmentMaintenance.class,mappedBy = "maintainence", cascade = CascadeType.MERGE, orphanRemoval = true, fetch = FetchType.EAGER)
	private Set<AttachmentMaintenance> attachments = new HashSet<AttachmentMaintenance>();

	public Long getId() {
		return this.id;
	}

	public void setId(final Long id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(final int version) {
		this.version = version;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!(obj instanceof Maintainence)) {
			return false;
		}
		Maintainence other = (Maintainence) obj;
		if (id != null) {
			if (!id.equals(other.id)) {
				return false;
			}
		}
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	public Item getItem() {
		return item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getDueDate() {
		return dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public String getMalfunctioning() {
		return malfunctioning;
	}

	public void setMalfunctioning(String malfunctioning) {
		this.malfunctioning = malfunctioning;
	}

	public Double getFees() {
		return fees;
	}

	public void setFees(Double fees) {
		this.fees = fees;
	}

	public String getMaintenanceMan() {
		return maintenanceMan;
	}

	public void setMaintenanceMan(String maintenanceMan) {
		this.maintenanceMan = maintenanceMan;
	}

	@Override
	public String toString() {
		String result = getClass().getSimpleName() + " ";
		if (malfunctioning != null && !malfunctioning.trim().isEmpty())
			result += "malfunctioning: " + malfunctioning;
		if (fees != null)
			result += ", fees: " + fees;
		if (maintenanceMan != null && !maintenanceMan.trim().isEmpty())
			result += ", maintenanceMan: " + maintenanceMan;
		return result;
	}

	public void newItem() {
		this.item = new Item();
	}

	/**
	 * @return the attachments
	 */
	public Set<AttachmentMaintenance> getAttachments() {
		return attachments;
	}

	/**
	 * @param attachments
	 *            the attachments to set
	 */
	public void setAttachments(Set<AttachmentMaintenance> attachments) {
		this.attachments = attachments;
	}

	/**
	 * @return the maintenanceCompany
	 */
	public Company getMaintenanceCompany() {
		return maintenanceCompany;
	}

	/**
	 * @param maintenanceCompany
	 *            the maintenanceCompany to set
	 */
	public void setMaintenanceCompany(Company maintenanceCompany) {
		this.maintenanceCompany = maintenanceCompany;
	}

}

src/main/java/org/D7noun/view/PersonBean.java
package org.D7noun.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Named;

import org.D7noun.facade.PersonFacade;
import org.D7noun.facade.RentalCardFacade;
import org.D7noun.facade.UnitFacade;
import org.D7noun.model.Person;
import org.D7noun.model.RentalCard;
import org.D7noun.model.Unit;
import org.D7noun.util.CommonUtility;

@Named
@SessionScoped
public class PersonBean implements Serializable {

	private static final long serialVersionUID = 1L;

	/*
	 * Support creating and retrieving Person entities
	 */

	@EJB
	private RentalCardFacade rentalCardFacade;
	@EJB
	private PersonFacade personFacade;
	@EJB
	private UnitFacade unitFacade;
	private Long id;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	private Person person;

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String create() {

		this.id = null;
		return "create?faces-redirect=true";
	}

	public void retrieve() {

		if (FacesContext.getCurrentInstance().isPostback()) {
			return;
		}

		if (this.id == null) {
			this.person = this.example;
		} else {
			this.person = findById(getId());
			fillDepartmentsByUnit();
		}
	}
	public String clearSearch() {
		this.example=new Person();
		return null;
	}
	public Person findById(Long id) {

		return personFacade.find(id);
	}

	/*
	 * Support updating and deleting Person entities
	 */

	public String update() {
		// this.conversation.end();

		try {
			if (this.person.getUnit() == null)
				throw new Exception("The unit is required");
			personFacade.save(this.person);
			this.example = new Person();
			return "search?faces-redirect=true";

		} catch (Exception e) {

			if (e.getCause() != null && e.getCause().getCause() != null && e.getCause().getCause().getCause() != null) {

				if (e.getCause().getCause().getCause().getMessage()
						.contains("duplicate key value violates unique constraint"))
					FacesContext.getCurrentInstance().addMessage(null,
							new FacesMessage("there is already a person with this pid"));
				else
					FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			} else {
				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));

			}
			return null;
		}
	}

	public String delete() {

		try {
			Person deletableEntity = findById(getId());
			Unit unit = deletableEntity.getUnit();
			if (unit != null) {
				unit.getPersons().remove(deletableEntity);
				deletableEntity.setUnit(null);
				unitFacade.save(unit);
			}

			RentalCard rentalCard = deletableEntity.getRentalCard();
			if (rentalCard != null) {
				rentalCard.setUser(null);
				rentalCardFacade.save(rentalCard);
			}
			personFacade.remove(deletableEntity);
			// personFacade.
			return "search?faces-redirect=true";
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			return null;
		}
	}

	/*
	 * Support searching Person entities with pagination
	 */

	private int page;
	private long count;
	private List<Person> pageItems;

	private Person example = new Person();

	public int getPage() {
		return this.page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getPageSize() {
		return 10;
	}

	public Person getExample() {
		return this.example;
	}

	public void setExample(Person example) {
		this.example = example;
	}

	public String search() {
		this.page = 0;
		return null;
	}

	public void paginate() {

		this.count = personFacade.getCount(this.example);

		this.pageItems = personFacade.getPaginatedList(this.page, getPageSize(), this.example);

	}

	public List<Person> getPageItems() {
		return this.pageItems;
	}

	public long getCount() {
		return this.count;
	}

	public List<Person> getAll() {

		return personFacade.getAll();
	}

	public Converter getConverter() {

		return new Converter() {

			@Override
			public Object getAsObject(FacesContext context, UIComponent component, String value) {

				return personFacade.find(Long.valueOf(value));
			}

			@Override
			public String getAsString(FacesContext context, UIComponent component, Object value) {

				if (value == null) {
					return "";
				}

				return String.valueOf(((Person) value).getId());
			}
		};
	}

	/*
	 * Support adding children to bidirectional, one-to-many tables
	 */

	private Person add = new Person();

	public Person getAdd() {
		return this.add;
	}

	public Person getAdded() {
		Person added = this.add;
		this.add = new Person();
		return added;
	}

	/**
	 * 
	 * D7noun
	 * 
	 */

	private List<String> departments = new ArrayList<String>();
	private List<String> facilityLocations = new ArrayList<String>();

	public void fillDepartmentsByUnit() {
		if (person != null && person.getUnit() != null) {
			departments=new  ArrayList<>();
			departments = CommonUtility.getListFromString(person.getUnit().getDepartments());
			facilityLocations=new ArrayList<>();
			facilityLocations = CommonUtility.getListFromString(person.getUnit().getFacilityLocation());

			
		}
	}
	
	/**
	 * @return the departments
	 */
	public List<String> getDepartments() {
		return departments;
	}

	public List<String> getFacilityLocations() {
		return facilityLocations;
	}

	public void setFacilityLocations(List<String> facilityLocations) {
		this.facilityLocations = facilityLocations;
	}

	/**
	 * @param departments
	 *            the departments to set
	 */
	public void setDepartments(List<String> departments) {
		this.departments = departments;
	}

}

src/main/webapp/maintainence/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:forgeview="http://jboss.org/forge/view"
	xmlns:p="http://primefaces.org/ui"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{maintainenceBean.id}' />
		<f:event type="preRenderView" listener='#{maintainenceBean.retrieve}' />
	</f:metadata>

	<ui:param name="pageTitle" value="Create Maintainence" />

	<ui:define name="header">
		Maintainence
	</ui:define>

	<ui:define name="subheader">
		<c:choose>
			<c:when test='#{!empty maintainenceBean.id}'>
				Edit existing Maintainence
			</c:when>
			<c:otherwise>
				Create a new Maintainence
			</c:otherwise>
		</c:choose>
	</ui:define>

	<ui:define name="footer" />

	<ui:define name="main">
		<h:outputStylesheet name="font-awesome/css/font-awesome.css" />

		<h:form id="create">

			<h:outputStylesheet name="css/attachment.css" />
			<h:outputStylesheet name="css/selectOneMenu.css" />

			<h:messages globalOnly="true" styleClass="error" />

			<div class="col-md-6">
				<div class="row">

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="maintainenceBeanMaintainenceItem" value="Item: *" />
							</div>
							<div class="col-md-7">
								<p:selectOneMenu id="maintainenceBeanMaintainenceItem"
									value="#{maintainenceBean.maintainence.item}" filter="true"
									filterMatchMode="contains" autoWidth="true"
									converter="#{itemConverter}" required="true"
									requiredMessage="Empty Maintenance Item">
									<f:selectItem />
									<f:selectItems value="#{itemBean.all}" var="item"
										itemValue="#{item}" itemLabel="#{item.displayName()}" />
								</p:selectOneMenu>
								<h:message for="maintainenceBeanMaintainenceItem"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="maintainenceBeanMaintainenceStartDate" value="Start Date:" />
							</div>
							<div class="col-md-7">
								<p:calendar id="maintainenceBeanMaintainenceStartDate"
									value="#{maintainenceBean.maintainence.startDate}" />
								<h:message for="maintainenceBeanMaintainenceStartDate"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="maintainenceBeanMaintainenceEndDate" value="End Date:" />
							</div>
							<div class="col-md-7">
								<p:calendar id="maintainenceBeanMaintainenceEndDate"
									value="#{maintainenceBean.maintainence.endDate}" />
								<h:message for="maintainenceBeanMaintainenceEndDate"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="maintainenceBeanMaintainenceDueDate" value="Due Date:" />
							</div>
							<div class="col-md-7">
								<p:calendar id="maintainenceBeanMaintainenceDueDate"
									value="#{maintainenceBean.maintainence.dueDate}" />
								<h:message for="maintainenceBeanMaintainenceDueDate"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="maintainenceBeanMaintainenceMalfunctioning"
									value="Malfunctioning:" />
							</div>
							<div class="col-md-7">
								<h:inputText styleClass="form-control"
									id="maintainenceBeanMaintainenceMalfunctioning"
									value="#{maintainenceBean.maintainence.malfunctioning}" />
								<h:message for="maintainenceBeanMaintainenceMalfunctioning"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="maintainenceBeanMaintainenceFees" value="Fees:" />
							</div>
							<div class="col-md-7">
								<p:inputNumber id="maintainenceBeanMaintainenceFees"
									value="#{maintainenceBean.maintainence.fees}"
									inputStyleClass="form-control" styleClass="money" symbol="$"
									symbolPosition="s" decimalSeparator="." thousandSeparator=","
									minValue="0" />
								<h:message for="maintainenceBeanMaintainenceFees"
									styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="maintenanceBeanCompany" value="Maintenance Company:" />
							</div>
							<div class="col-md-7">
								<p:selectOneMenu id="maintenanceBeanCompany"
									value="#{maintainenceBean.maintainence.maintenanceCompany}"
									filterMatchMode="contains" filter="true"
									converter="#{companyConverter}">
									<f:selectItem />
									<f:selectItems value="#{companyBean.all}" var="company"
										itemLabel="#{company.name}" itemValue="#{company}" />
									<p:ajax update="maintainenceBeanMaintainenceMaintenanceMan"
										listener="#{maintainenceBean.fillEmployeesFromCompany()}" />
								</p:selectOneMenu>
								<h:message for="maintenanceBeanCompany" styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-12">
							<div class="col-md-5">
								<h:outputLabel styleClass="control-label"
									for="maintainenceBeanMaintainenceMaintenanceMan"
									value="Maintenance Man:" />
							</div>
							<div class="col-md-7">
								<p:selectOneMenu id="maintainenceBeanMaintainenceMaintenanceMan"
									value="#{maintainenceBean.maintainence.maintenanceMan}"
									filterMatchMode="contains" filter="true">
									<f:selectItem />
									<f:selectItems value="#{maintainenceBean.employees}"
										var="employee" itemLabel="#{employee}" itemValue="#{employee}" />
								</p:selectOneMenu>
								<h:message for="maintainenceBeanMaintainenceMaintenanceMan"
									styleClass="error" />
							</div>
						</div>
					</div>

				</div>
			</div>

			<div class="col-md-6">

				<p:dataTable id="attachmentsDataTable" widgetVar="attachmentVar"
					rows="5" paginator="true"
					paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
					rowsPerPageTemplate="5,10,15,20,50" paginatorAlwaysVisible="false"
					paginatorPosition="bottom"
					value="#{maintainenceBean.maintainence.attachments}"
					var="attachment" rowKey="#{attachment.id}" rowIndexVar="index"
					editable="true" editMode="cell">

					<f:facet name="header">

						<h:outputText value="Attachments"
							styleClass="attachmentHeaderText" />

						<p:fileUpload widgetVar="fileUploadVar" multiple="true"
							auto="true" styleClass="fileUploader hide"
							fileUploadListener="#{maintainenceBean.handleFileUpload}"
							process="@this" update="attachmentsDataTable" />

						<h:commandLink onclick="$('.fileUploader input').click()"
							styleClass="btn btn-primary white attachmentHeaderButton">
							<f:ajax />
							<i class="fa fa-plus white" />
						</h:commandLink>

					</f:facet>

					<p:column id="index" width="50">
						<h:outputText value="#{index+1}"></h:outputText>
					</p:column>

					<p:column id="actions" width="50">
						<h:commandLink styleClass="btn btn-sm btn-danger white"
							action="#{maintainenceBean.selectForDelete(attachment)}"
							onclick="PF('deleteDialogVar').show()">
							<i class="fa fa-trash white" />
							<f:ajax />
						</h:commandLink>
					</p:column>

					<p:column id="attachmentName" headerText="Name"
						filterMatchMode="contains" filterBy="#{attachment.fileName}"
						sortBy="#{attachment.fileName}" styleClass="attachmentName-column"
						width="">
						<h:outputText value="#{attachment.fileName}"
							title="#{attachment.fileName}" />
					</p:column>

					<p:column id="attachmentSize" headerText="Size"
						sortBy="#{attachment.size}" style="text-align: center">
						<h:outputText title="#{attachment.sizeInMegaByte}"
							value="#{attachment.sizeInMegaByte}" />
					</p:column>

					<p:column id="description" headerText="Description"
						filterMatchMode="contains" filterBy="#{attachment.description}"
						sortBy="#{attachment.description}"
						styleClass="attachmentDescription-column">
						<h:inputText value="#{attachment.description}"
							styleClass="form-control" />
					</p:column>

					<p:column id="notes" headerText="Notes" filterMatchMode="contains"
						filterBy="#{attachment.notes}" sortBy="#{attachment.notes}"
						styleClass="attachmentNotes-column" width="">
						<h:inputText value="#{attachment.notes}" styleClass="form-control" />
					</p:column>

					<p:column width="50">
						<h:commandLink action="#{maintainenceBean.download(attachment)}"
							styleClass="btn btn-sm btn-primary">
							<i class="fa fa-download white" />
						</h:commandLink>
					</p:column>

				</p:dataTable>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="buttons">
						<h:commandLink value="Save" action='#{maintainenceBean.update}'
							styleClass="btn btn-primary" />
						<c:choose>
							<c:when test='#{!empty maintainenceBean.id}'>
								<h:link value="Cancel" outcome="search"
									styleClass="btn btn-warning">
								</h:link>
								<h:commandLink value="Delete"
									action='#{maintainenceBean.delete}' styleClass="btn btn-danger" />
							</c:when>
							<c:otherwise>
								<h:link value="Cancel" outcome="search"
									styleClass="btn btn-warning" />
							</c:otherwise>
						</c:choose>
						<p:commandLink value="Print" action="#{maintainenceBean.print()}"
							styleClass="btn btn-info" ajax="false">
						</p:commandLink>
					</div>
				</div>
			</div>

			<script type="text/javascript" src="../resources/js/selectOneMenu.js" />
			<script type="text/javascript" src="../resources/js/calendar.js" />

			<p:dialog id="deleteDialog" draggable="false" closable="false"
				modal="true" height="50" width="310" resizable="false"
				widgetVar="deleteDialogVar">


				<f:facet name="header">
					<h:outputText value="Confirm Deletion????" />
				</f:facet>

				<h:commandLink value="Ok"
					action="#{maintainenceBean.deleteAttachment()}"
					onclick="PF('deleteDialogVar').hide()"
					styleClass="btn btn-primary popup-buttons">
					<f:ajax render="attachmentsDataTable" />
				</h:commandLink>
				<h:commandLink value="Cancel"
					styleClass="btn btn-danger popup-buttons"
					onclick="PF('deleteDialogVar').hide()">
					<f:ajax />
				</h:commandLink>
			</p:dialog>
		</h:form>
	</ui:define>

</ui:composition>